#Author: LEANDRO ARISTIDE #

##Creates a colormap depicting differences between two ply meshes.
##Should be superimposed previously and have the same number of vertices (e.g. from warping one mesh into another shape)
########
##can use a color scale supplied by the user (fix_scale = T)
##e.g. generated by the same function for other transformation
##scale_df = object with color scale previously generated by same function (ret_scale = T)
##this way color values are "absolute" and different shapes can be compared
##reference color scale should be generated for the two most dissimilar shapes
##use carefully
#####
#x,y ply file names
#colors in rgb code (example c(250,50,20))
colormap<-function(x,y,col1, col2, file="out", plot_scale = T, ret_scale = F, fix_scale = F, scale_df = NULL){
  
  color1 <- t(as.matrix(col1))
  color2 <- t(as.matrix(col2))
  out <- paste(file,".ply", sep = "")
  
  hdr <- grep("end_header",readLines(x, n =25,encoding = "unknown"),value=F)
  col.vrtx <- grep("element vertex",readLines(x, n =20,encoding = "unknown"),value=F)
  vrtx <- read.csv(x,sep=" ",dec=".",header=F,nrows=1,colClasses=c("character","character","numeric"),skip=col.vrtx-1)[1,3]
  
  ncol <- max(count.fields(x,skip=hdr,sep = " "))
  m1 <- read.table(x,sep=" ",dec=".",header=F,skip=hdr,nrows=vrtx)
  ncol <- max(count.fields(y,sep = " "))
  m2 <- read.table(y,sep=" ",dec=".",header=F,skip=hdr,nrows=vrtx)
  
  #radial distances difference between each point pair (spherical coordinates)
  distrpol <- sqrt(m1[,1]^2 + m1[,2]^2 + m1[,3]^2) - sqrt(m2[,1]^2 + m2[,2]^2 + m2[,3]^2)
  
  #generates color gradiente and assigns each vertex to a color according to distrpol
  if (fix_scale == T){
    max_col <- as.vector(scale_df[which.min(abs(max(distrpol) - scale_df[,2])),1])
    min_col <- as.vector(scale_df[which.min(abs(min(distrpol) - scale_df[,2])),1])
    colores <- colorRampPalette(c(min_col,"gray",max_col))
    vert_col <- colores(n=500)[as.numeric(cut(distrpol,breaks=500))]
    vert_col_rgb <- t(col2rgb(vert_col,alpha = F))
    m3 <- cbind(m1[,1:3],vert_col_rgb)
  } else {
      colores <- colorRampPalette(c(rgb(r=color1, max=255),"gray",rgb(color2, max=255)))
      vert_col <- colores(n=500)[as.numeric(cut(distrpol,breaks=500))]
      vert_col_rgb <- t(col2rgb(vert_col,alpha = F))
      m3 <- cbind(m1[,1:3],vert_col_rgb)
    }
  
  ########### writes ply
  ply_header <- read.csv(x,sep=" ",dec=".",header=F,col.names =c(1,2,3,4,5,6,7,8),nrows=hdr)
  ply_faces <- read.csv(x,sep=" ",dec=".",header=F,col.names =c(1,2,3,4,5,6,7,8),skip=(hdr+vrtx))
  write.table(ply_header,file = out,row.names=F,col.names=F,na="",quote=F)
  write.table(m3,file = out,row.names=F,col.names=F,na="",append=T,quote=F)
  write.table(ply_faces,file = out,row.names=F,col.names=F,na="",append=T)
  
  ####plots used color scale
  if (plot_scale == T){
    library(plot3D)
    plot.new()
    colkey(col=colores(500), side = 2, clim =range(distrpol), dist=-0.5)
  }
  #returns color scale to use in another colormap
  if (ret_scale == T){
    return(cbind(vert_col, data.frame(distrpol)))
  }
}

# color1<-c(153,208,212)
# color2<-c(224,135,57)
